---
app_name: ExampleApp

root: /home/user42/sounds
data: /home/user42/sounds/.catalog
logging: /home/user42/sounds/.catalog/logs
log_level: debug
covers: /home/user42/sounds/.catalog/covers
intake: /home/user42/sounds/.sort
